name: Deploy Laravel Backend

on:
  push:
    branches: ["12.x"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Backend Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.BACKEND_HOST }}
          username: ${{ secrets.BACKEND_USER }}
          key: ${{ secrets.BACKEND_KEY }}
          script: |
            cd /var/www/backend-app
            sudo git pull origin 12.x
            composer install --no-interaction --prefer-dist
            php artisan migrate --force
            php artisan optimize
            sudo systemctl restart php8.2-fpm
            sudo systemctl restart nginx
